server:
  port: 9001
  servlet:
    context-path: /store

#  数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hjq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#    数据源使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间，单位：毫秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: ture
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 30
    filters: stat,wall

#  mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.hjq.web.demo.pojo


# 缓存配置
redis:
  host: localhost
  port: 6379
  password:
  minIdle: 3
  maxIdle: 5
  timeout: 100
  maxWaitMillis: 8000


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#过滤配置
filter:
  excludePath: /stroe/exoteric/login,/stroe/exoteric/register
  logoutPath: /logout